name = "pytoday-api"
main = "src/index.js"
compatibility_date = "2025-11-20"

[vars]
# Ye proxies tune diye hain â€“ hum inko rotate karenge
PROXIES = '[
  "socks5://KkQ7ob2myPlER2WE:KkQ7ob2myPlER2WE@109.104.153.100:12081",
  "socks5://cbzPi5W8ut8kwVc6:cbzPi5W8ut8kwVc6@109.104.153.29:11657",
  "socks5://gHw4zueog2SxDYRn:gHw4zueog2SxDYRn@109.104.153.29:10094"
]'

# Optional: Cache duration (seconds)
CACHE_TTL = "31536000"  # 1 year for images
